# Use the random.normal() method to get a Normal Data Distribution.

# Generate a random normal distribution of size 2x3:
from numpy import random

x = random.normal(size=(2, 3))
print(x)

# Generate a random normal distribution of size 2x3 with mean at 1 and standard deviation of 2:

x = random.normal(loc=1, scale=2, size=(2, 3)) # loc for the meaan for the normal distribution and scale for the standard distribution 
                                               # size is the shape of the array 
print(x)

# Visualization of Normal Distribution

from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.distplot(random.normal(size=1000), hist=False) # here hist is false so histogram is not present
plt.show() # for showing the graph which is generated by matplotlib pyplot
